export const appConstants = {
  name: "Tuvu",
  localAttributionUrl: "/",
} as const;

export const externalApiEndpoints = {
  githubAuthorize: "https://github.com/login/oauth/authorize",
  githubToken: "https://github.com/login/oauth/access_token",
  githubUser: "https://api.github.com/user",
  tmdbApi: "https://api.themoviedb.org/3",
  tmdbWeb: "https://www.themoviedb.org",
  tmdbImage: "https://image.tmdb.org/t/p",
  tvmazeApi: "https://api.tvmaze.com",
  tvmazeWeb: "https://www.tvmaze.com",
  wikidataApi: "https://www.wikidata.org/wiki/Special:EntityData",
  theTvDbApi: "https://api4.thetvdb.com/v4",
  theTvDbWeb: "https://thetvdb.com",
  aniListGraphQL: "https://graphql.anilist.co",
  googleBooksApi: "https://www.googleapis.com/books/v1",
  twitchOAuthToken: "https://id.twitch.tv/oauth2/token",
  igdbGames: "https://api.igdb.com/v4/games",
  igdbWeb: "https://www.igdb.com",
  igdbImage: "https://images.igdb.com/igdb/image/upload",
  rawgApi: "https://api.rawg.io/api",
  rawgWeb: "https://rawg.io",
  openLibrary: "https://openlibrary.org",
  openLibraryCovers: "https://covers.openlibrary.org",
  musicBrainzApi: "https://musicbrainz.org/ws/2",
  coverArtArchiveApi: "https://coverartarchive.org",
  listenBrainzApi: "https://api.listenbrainz.org/1",
  theAudioDbApi: "https://www.theaudiodb.com/api/v1/json",
  lrclibApi: "https://lrclib.net/api",
  gdeltApi: "https://api.gdeltproject.org/api/v2/doc/doc",
  guardianApi: "https://content.guardianapis.com",
  newsApi: "https://newsapi.org/v2",
  openSubtitlesApi: "https://api.opensubtitles.com/api/v1",
  jikanApi: "https://api.jikan.moe/v4",
  myAnimeList: "https://myanimelist.net",
  youtubeWeb: "https://www.youtube.com",
  youtubeApi: "https://www.googleapis.com/youtube/v3",
} as const;

export const providerNames = {
  tmdb: "TMDB",
  tvmaze: "TVmaze",
  wikidata: "Wikidata",
  thetvdb: "TheTVDB",
  jikan: "MyAnimeList (Jikan)",
  anilist: "AniList",
  googlebooks: "Google Books",
  openlibrary: "Open Library",
  igdb: "IGDB",
  rawg: "RAWG",
  musicbrainz: "MusicBrainz",
  coverartarchive: "Cover Art Archive",
  listenbrainz: "ListenBrainz",
  theaudiodb: "TheAudioDB",
  lrclib: "LRCLIB Lyrics",
  gdelt: "GDELT",
  guardian: "The Guardian",
  newsapi: "NewsAPI",
  opensubtitles: "OpenSubtitles",
  youtube: "YouTube",
  local: appConstants.name,
} as const;

export const uiConstants = {
  cacheStoragePrefix: "tuvu-query:",
  themeStorageKey: "tuvu-theme",
  noticeEventName: "tuvu:notice",
  defaultPosterAccent: "linear-gradient(145deg, #30343b, #111318)",
} as const;

export const designTokenNames = {
  colorBg: "--color-bg",
  colorText: "--color-text",
  colorAccent: "--color-accent",
  radiusCard: "--radius-card",
  shellTopbarHeight: "--shell-topbar-height",
  shellBottomNavHeight: "--shell-bottom-nav-height",
} as const;
